package com.redtermapp.ui

import android.app.Activity
import android.content.Context
import android.text.InputType
import android.widget.EditText
import androidx.appcompat.app.AlertDialog
import com.redtermapp.R
import com.redtermapp.util.sftp.SshAskpass
import java.util.concurrent.CountDownLatch
import java.util.concurrent.TimeUnit

/**
 * Supplies a key passphrase to a connection that has no terminal to ask on its own.
 *
 * The passphrase is only requested when a connection has actually been refused,
 * rather than from a flag recorded when the key was made. That flag cannot be
 * trusted: a key pasted in from elsewhere, one generated by an older build of the
 * app, or one whose passphrase was changed afterwards all say "no passphrase" and
 * then fail with an error that reads as the server refusing the key. Reacting to
 * the failure gets all of those right, and does not ask about a key that never
 * needed it.
 *
 * The phrase is held in memory for the life of the process and is never written to
 * disk or to preferences.
 */
object SshKeyUnlock {

    /** A phrase held for [key], or an empty string when there is none. */
    fun availableFor(key: SshKeyStore.Entry): String = SshAskpass.cached(key.fileName) ?: ""

    /**
     * Asks for the passphrase of one named key and returns it, or null if there was
     * no answer.
     *
     * Meant to be called from a worker: the dialog is shown on the main thread and
     * this blocks until it is dismissed, which is the one thing a worker may do and
     * the main thread may not.
     *
     * Blocking until the dialog is *dismissed* rather than merely shown is the whole
     * point. An AlertDialog answers through a callback that runs after this method
     * would otherwise have returned, so a read straight after `show()` sees nothing,
     * the connection is retried with no passphrase, and the user is left watching a
     * dialog they already answered followed by the same refusal as before.
     *
     * One key at a time, deliberately: `SSH_ASKPASS` supplies a phrase with no way
     * to say which key it is for, so a connection must ask about the key it is
     * actually trying rather than offer several and let the answer land on the
     * wrong one.
     */
    fun requestPassphraseBlocking(activity: Activity, key: SshKeyStore.Entry): String? {
        if (activity.isFinishing || activity.isDestroyed) return null
        if (SshAskpass.isDeclined(key.fileName)) return null
        // One dialog at a time. Two operations can overlap — a listing still running
        // while a transfer starts — and two stacked prompts mean the answer to the
        // second is typed into the first.
        synchronized(promptLock) {
            if (SshAskpass.isDeclined(key.fileName)) return null
            if (activity.isFinishing || activity.isDestroyed) return null
            return ask(activity, key)
        }
    }

    private fun ask(activity: Activity, key: SshKeyStore.Entry): String? {

        val answer = AnswerLatch<String?>()
        activity.runOnUiThread {
            // Re-checked here: the activity can finish between the call and its
            // turn on the main thread, and a dialog on a dead activity throws.
            if (activity.isFinishing || activity.isDestroyed) {
                answer.complete(null)
                return@runOnUiThread
            }
            showDialog(activity, key, answer)
        }
        val phrase = answer.await(TIMEOUT_SECONDS)
        if (phrase.isNullOrEmpty()) {
            // Dismissed or left blank: recorded so the next operation does not ask
            // the same question again.
            SshAskpass.decline(key.fileName)
            return null
        }
        SshAskpass.remember(key.fileName, phrase)
        return phrase
    }

    private fun showDialog(activity: Activity, key: SshKeyStore.Entry, answer: AnswerLatch<String?>) {
        val field = EditText(activity).apply {
            // Not the "Passphrase (optional)" hint: nothing here is optional, and a
            // prompt that offers an empty answer for a key that needs one is a good
            // way to be refused for ever.
            hint = activity.getString(R.string.ssh_key_passphrase_required)
            inputType = InputType.TYPE_CLASS_TEXT or InputType.TYPE_TEXT_VARIATION_PASSWORD
            setSingleLine(true)
        }
        var entered: String? = null
        AlertDialog.Builder(activity)
            .setTitle(activity.getString(R.string.ssh_key_unlock_title, key.label))
            .setMessage(R.string.ssh_key_unlock_message)
            .setView(SecretField.withRevealToggle(activity, field))
            .setPositiveButton(R.string.ok) { _, _ -> entered = field.text.toString() }
            .setNegativeButton(R.string.cancel) { _, _ -> entered = null }
            .create()
            .apply {
                // Dismissal, not the button: the dialog can also go away by a tap
                // outside it or a back press, and every one of those paths has to
                // release the worker thread instead of hanging it.
                setOnDismissListener { answer.complete(entered) }
                show()
            }
    }

    /** Forgets every held phrase, e.g. when a key is deleted. */
    fun forgetAll() = SshAskpass.forgetAll()

    /**
     * A value that arrives later, on another thread.
     *
     * Exists so the "wait for an answer that has not been given yet" rule is one
     * tested object rather than a pattern repeated at each call site, where getting
     * it wrong is invisible: the read returns an empty value and the caller carries
     * on as though the user had declined.
     */
    internal class AnswerLatch<T> {
        private val latch = CountDownLatch(1)

        @Volatile
        private var value: T? = null

        fun complete(with: T) {
            value = with
            latch.countDown()
        }

        fun await(seconds: Long): T? {
            return if (latch.await(seconds, TimeUnit.SECONDS)) value else null
        }
    }

    private val promptLock = Object()

    /**
     * Bounded so a dialog that never appears cannot leave a transfer thread stuck
     * for ever. Long enough for a real person to type a passphrase.
     */
    private const val TIMEOUT_SECONDS = 180L
}